### ISSUE TITLE
Windows - Makes huge zip files

### ISSUE THREAD

**Issue by roytruelove** [twolfson/grunt-zip#16]
Node v 0.10.13
grunt-zip 0.9.2

Plugin creates a 16meg file, but when compressed (and before compression), the size is about 500k.

Config:

```
zip:
    dist:
        expand: true
        cwd: 'bower'
        src: ['**/*.*']
        dest: 'target/dist/bower.zip'
```
